Coding challenge - Dot Product with matrix columns

In [10]:
import numpy as np
import matplotlib.pyplot as plt
import mpl_toolkits.mplot3d as mplot3d

In [11]:
# Create 2 4x6 matrix of random numbers
# Use a for-loop to compute dot products between corresponding columns

m = 4
n = 6

mat1 = np.random.randn(m,n)
mat2 = np.random.randn(m,n)

print(mat1)
print(mat1.shape)
print()
print(mat2)
print(mat2.shape)

[[-0.99958696  0.69944638  0.37306798  0.6918397  -0.41492764  0.24771944]
 [ 0.90342678  0.69920067 -0.6355275  -0.98076454  0.38357445 -0.37261507]
 [ 0.67389954  1.06230196  0.97557978  0.17644301  1.24836613  0.34934919]
 [-0.87492458 -1.08735837 -0.66702001 -0.18442943 -1.00000076 -0.26926967]]
(4, 6)

[[ 0.47595415  0.37918756  0.01951591 -0.70624096  0.78574084 -1.06306035]
 [ 0.22878936 -0.26279371  0.74041788  0.56309892  1.12391761  2.04607105]
 [-0.70082423  1.64090314  1.14551246  0.48365586  0.62045919 -0.40037326]
 [ 2.63731801  0.23391823  0.01501656  1.66327856 -0.46560341 -1.7912917 ]]
(4, 6)


In [12]:
dps = np.zeros(n)

for i in range(n):
    dps[i] = np.dot(mat1[:,i], mat2[:,i])

print(dps)


[-3.04880258  1.57025751  0.64424728 -1.26229281  1.34524449 -0.68326715]
