Vector Hadamard multiplication

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import mpl_toolkits.mplot3d as mplot3d

In [3]:
w1 = [1, 3, 5]
w2 = [3, 4, 2]

w3 = np.multiply(w1, w2)

print(w3)

[ 3 12 10]


Outer Product

In [7]:
v1 = np.array([1,2,3])
v2 = np.array([-1,0,1])

# Outer Product
v3 = np.outer(v1, v2)

print(v3)

op = np.zeros((len(v1), len(v2)))
for i in range(0, len(v1)):
    for j in range(0, len(v2)):
        op[i, j] = v1[i] * v2[j]

print()
print(op)

[[-1  0  1]
 [-2  0  2]
 [-3  0  3]]

[[-1.  0.  1.]
 [-2.  0.  2.]
 [-3.  0.  3.]]
