In [1]:
import numpy as np

# A Zoo of Matrices

In [4]:
# Square vs Rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2)
print(S), print(' ')
print(R)

[[ 3.4662992   1.57048739 -0.13750997 -1.24478142 -0.32852211]
 [-1.42397073  0.35327899 -0.26948029  1.1410042   1.26851324]
 [ 0.55559612 -0.08163081  1.64895994 -0.68301923  0.18602059]
 [ 1.37816541  0.21365182  2.04029386  1.4962988   0.61047629]
 [ 1.987062    0.99165599 -2.23041602 -0.45530999  1.58652231]]
 
[[-1.03529891 -0.25611167]
 [-0.51620022 -1.02837095]
 [ 0.44025529  0.14626364]
 [ 1.616982    1.76299   ]
 [-1.42903073  0.69356658]]


In [8]:
# Identity
I = np.eye(3,3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# zeros
# Z = np.zeros((4,4))
Z = np.zeros((4,4), dtype=complex)
print(Z)

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [19]:
# Diagonal
D = np.diag([1,2,3,5,2])
print(D)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]


In [21]:
# Triangular Matrix from Full matrix
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(U), print(' ')
print(L)

[[ 0.39290444 -0.25933819  0.2903036   0.00215317 -2.1505944 ]
 [ 0.          0.92583406 -0.7692545  -0.18202583  0.71364917]
 [ 0.          0.          0.48586838  1.23333001 -0.39918469]
 [ 0.          0.          0.          0.54002407  1.02168215]
 [ 0.          0.          0.          0.         -0.45736702]]
 
[[ 0.39290444  0.          0.          0.          0.        ]
 [ 0.72559159  0.92583406  0.          0.          0.        ]
 [ 0.70001971  0.16791022  0.48586838  0.          0.        ]
 [ 0.66745798  0.56296512 -0.95181775  0.54002407  0.        ]
 [ 0.9202728   0.50941737 -0.20242959 -0.81264467 -0.45736702]]


In [29]:
# Concatenate Matrices
A = np.random.randn(3,2)
B = np.random.randn(3,4)
C = np.concatenate((A,B), axis=1)
print(C), print(' ')

[[-0.7566771  -0.37135934 -0.09698284  0.42733039 -0.42441567  0.77308968]
 [-0.01233281 -0.30343143  2.32152651 -0.41684415  0.69137108 -0.10777601]
 [ 1.13662919 -0.10388874 -1.46869189  0.1652407   0.8213782   0.14226973]]
 


(None, None)