# Matrix Addition and Substraction

In [2]:
import numpy as np

In [7]:
# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

#A + B
A + C

array([[-1.03234474,  3.17301303, -0.82262256,  1.83169103],
       [-0.91711651,  1.12995321, -2.45839252, -1.24291055],
       [ 2.18371593, -1.0690917 ,  1.33441091,  2.31592643],
       [-2.10912681, -0.77329826, -0.36963802, -1.54527154],
       [ 0.92519026, -0.71758773, -1.32000027,  1.03378344]])

In [9]:
# Shifting a matrix

l = 0.3
N = 5 # size of square matrix
D = np.random.randn(N, N)  # can only shift a square matrix

Ds = D + l * np.eye(N)
print(D), print(' '), print(Ds)

[[-0.62769881  0.89754814 -0.3238603  -0.32748858 -0.23909044]
 [-0.40677291 -0.23619709  2.51701199  0.14621877  0.98030746]
 [ 0.43926832 -0.728732   -1.06436872  0.54505903 -0.90269526]
 [ 0.451977   -0.48397024 -0.18841031  0.82300955 -0.05757806]
 [-0.72550812 -1.60914375  0.15424362  0.60947945 -1.25950328]]
 
[[-0.32769881  0.89754814 -0.3238603  -0.32748858 -0.23909044]
 [-0.40677291  0.06380291  2.51701199  0.14621877  0.98030746]
 [ 0.43926832 -0.728732   -0.76436872  0.54505903 -0.90269526]
 [ 0.451977   -0.48397024 -0.18841031  1.12300955 -0.05757806]
 [-0.72550812 -1.60914375  0.15424362  0.60947945 -0.95950328]]


(None, None, None)

In [11]:
# Matrix Scalar Multiplication

M = np.array([ [1,2], [2,5]])
s = 2

# pre and post multiplication is the same
print(M*s)
print(s*M)

[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]
