In [1]:
import numpy as np

In [6]:
M = np.array([ [1,2,3], [2,3,4] ])

print(M), print(' ')
print(M.T), print(' ')
print(M.T.T), print(' ')

# can also use the function transpose
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]
 
[[1 2]
 [2 3]
 [3 4]]
 
[[1 2 3]
 [2 3 4]]
 
[[1 2]
 [2 3]
 [3 4]]


In [11]:
# Warning: be careful when using complex matrices
C = np.array([ 4+1j, 3, 2-4j ])

print(C), print(' ')
print(C.T)
print(np.transpose(C))

# In python, we need to call Hermitian explicitly by first converting the complex conjugate and then flip
print(np.matrix(C).H)

[4.+1.j 3.+0.j 2.-4.j]
 
[4.+1.j 3.+0.j 2.-4.j]
[4.+1.j 3.+0.j 2.-4.j]
[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]
