In [2]:
import numpy as np

In [7]:
M = np.round(6* np.random.randn(4,4))

print(M), print(' ')
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M)
D = np.diag(d)

print(d)
print(D)

# trace as sum of diagonals
tr = np.trace(M)
tr2 = sum(np.diag(M))
print(' '), print(tr, tr2)

[[  0. -12.  13.   7.]
 [ 12.   9.   2.  -4.]
 [  6.  17.  -2. -11.]
 [  8.  -3.   2.   9.]]
 
[ 0.  9. -2.  9.]
[[ 0.  0.  0.  0.]
 [ 0.  9.  0.  0.]
 [ 0.  0. -2.  0.]
 [ 0.  0.  0.  9.]]
 
16.0 16.0


(None, None)