In [1]:
import numpy as np

In [8]:
A = np.reshape(np.arange(1,13), (3,4), 'F') # F = Columns, C = row

r = [10, 20, 30, 40]
c = [100, 200, 300]

print(A), print(' ')
print(r), print(' ')
print(c), print(' ')

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
 
[10, 20, 30, 40]
 
[100, 200, 300]
 


(None, None)

In [17]:
# broadcast on the rows
print(A + r), print(' ')

# broadcast on the columns
print( A + np.reshape(c, (len(c),1) ) ), print(' ') # only works for explicit column vectors


[[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]
 
[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]
 


(None, None)