In [1]:
import numpy as np

In [9]:
# test for some random MxN matrix whether s (A+B) = sA + sB

M = 5
N = 3
s = 5

A = np.random.randn(M, N)
B = np.random.randn(M, N)

C = s * (A + B)
D = (s*A) + (s*B)

print(C), print(' '), print(D)

print(D - C)

[[  9.92800236   6.78335362   0.69908483]
 [-11.17234128   4.42475575   6.27298389]
 [ -4.0757356    5.66771086   2.99009014]
 [  7.93359524   0.80991096  -6.729612  ]
 [ -2.03619986   2.9305735  -15.96715789]]
 
[[  9.92800236   6.78335362   0.69908483]
 [-11.17234128   4.42475575   6.27298389]
 [ -4.0757356    5.66771086   2.99009014]
 [  7.93359524   0.80991096  -6.729612  ]
 [ -2.03619986   2.9305735  -15.96715789]]
[[ 0.00000000e+00 -8.88178420e-16 -1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  4.44089210e-16]
 [ 8.88178420e-16  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -4.44089210e-16  1.77635684e-15]]
